# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - vinodtest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://vinodtest.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_691f564230a140d8a679800f67e0abe4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_69d5a3e1b9af48cfa9f21eb09b21c549 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: vinodtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_691f564230a140d8a679800f67e0abe4 }}/hello:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vinodtest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f4c5dbaa170a4bd68767b1eff72c8d74 }}
        images: 'vinodtest.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_691f564230a140d8a679800f67e0abe4 }}/hello:${{ github.sha }}'